server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice # order服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务端地址
        cluster-name: HZ #nacos集群名称
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel控制台地址
      web-context-unify: false # 是否统一控制台上下文(关闭context整合)
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848 # nacos服务端地址
            dataId: orderservice-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow # 规则类型
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    serviceUrl: # eureka的地址信息
#      defaultZone: http://localhost:10086/eureka/
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则(nacos集群)
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则(随机)
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
feign:
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 每个路由最大连接数
  sentinel:
    enabled: true # 开启feign对sentinel的支持